### ISSUE TITLE
SensuHandler not included in sensu_plugin

### ISSUE THREAD

**Issue by clouseau** [sensu-plugins/sensu-plugin-python#4] opened 2014-01-18 22:07 UTC
sensu_plugin at https://pypi.python.org/pypi/sensu_plugin/0.1.0 does not include handler.py.

So currently if you do

```
pip install sensu_plugin
```

and then try

```
from sensu_plugin.handler import SensuHandler
```

you will get an import error.

**Comment by hubricode** [comment] 2015-12-03 11:44
@zsprackett I am stuck here too. I've had to start using this plugin to support a sensu version upgrade, but I am stuck without a handler. Any updates / quick workarounds you'd like to recommend?

**Comment by majormoses** [comment] 2017-10-07 19:37
This is a duplicate of #1 which I am closing this favor of.

**Closed by majormoses** 2017-10-07 19:37 UTC
Labels: Status: Help Wanted, Type: Enhancement
